/* Англи хэлний дүрэм (CEFR A1–C1, IELTS бэлтгэл). IELTS.grammar-д нэмэгдэнэ. */
window.EN_GRAMMAR_MORE = {
  "A1": [
    { title: "There is / There are", explain: "«...байна» гэж оршихуйг илэрхийлнэ. Ганц тоонд there is, олон тоонд there are. Үгүйсгэл: there isn't / there aren't. Асуулт: Is there...? Are there...?",
      examples: [["There is a park near my house.", "Манай гэрийн ойролцоо цэцэрлэгт хүрээлэн бий."], ["There are 30 students in my class.", "Манай ангид 30 сурагч бий."]],
      quiz: [{ q: "___ two books on the table.", o: ["There is", "There are", "It is", "They are"], a: 1 }] },
    { title: "Have got / Has got — Эзэмших", explain: "«...-тэй байх» гэсэн утга. I/you/we/they have got, he/she/it has got. Ярианд have/has-ийг ганцаар нь ч хэрэглэнэ.",
      examples: [["I have got a brother.", "Би ахтай."], ["She has got blue eyes.", "Тэр цэнхэр нүдтэй."]],
      quiz: [{ q: "My father ___ a new car.", o: ["have got", "has got", "is got", "got have"], a: 1 }] },
    { title: "This / That / These / Those", explain: "Ойр байгаа нэг зүйл — this, олон — these. Хол байгаа нэг зүйл — that, олон — those.",
      examples: [["This is my phone.", "Энэ бол миний утас."], ["Those mountains are beautiful.", "Тэр уулс үзэсгэлэнтэй."]],
      quiz: [{ q: "___ shoes here are mine.", o: ["This", "That", "These", "Those"], a: 2 }] },
    { title: "Хамаатуулах: my, your, his... ба 's", explain: "Хамаатуулах тэмдэг нэр: my, your, his, her, its, our, their. Нэр үгэнд 's залгаж эзэмшлийг заана: Bat's bag. Олон тооны -s-тэй үгэнд зөвхөн ': my parents' house.",
      examples: [["This is my sister's room.", "Энэ бол миний эгчийн өрөө."], ["Their teacher is very kind.", "Тэдний багш их сайхан сэтгэлтэй."]],
      quiz: [{ q: "That is ___ book. (Сараагийн)", o: ["Saraa", "Saraas", "Saraa's", "Saraa is"], a: 2 }] },
    { title: "Нэр үгийн олон тоо", explain: "Ихэнхдээ -s (book → books). -s, -sh, -ch, -x-ээр төгссөнд -es (bus → buses). Гийгүүлэгч + y → -ies (city → cities). Онцгой: man → men, child → children, foot → feet, person → people.",
      examples: [["I have three boxes.", "Надад гурван хайрцаг бий."], ["Two children are playing.", "Хоёр хүүхэд тоглож байна."]],
      quiz: [{ q: "baby → ?", o: ["babys", "babyes", "babies", "babis"], a: 2 }, { q: "one woman, two ___", o: ["womans", "women", "womens", "woman"], a: 1 }] },
    { title: "Can / Can't — Чадвар", explain: "Can + үйл үгийн үндсэн хэлбэр. Бүх биед адилхан: I can, she can. Үгүйсгэл: can't (cannot). Асуулт: Can you...?",
      examples: [["I can swim.", "Би сэлж чадна."], ["She can't drive.", "Тэр машин барьж чадахгүй."]],
      quiz: [{ q: "He can ___ three languages.", o: ["speaks", "speak", "speaking", "to speak"], a: 1 }] },
    { title: "Тушаах өгүүлбэр (Imperatives)", explain: "Үйл үгийн үндсэн хэлбэрээр эхэлнэ: Open the door. Үгүйсгэл: Don't + үйл үг. Эелдэг болгохдоо please нэмнэ.",
      examples: [["Please sit down.", "Суугаарай."], ["Don't be late.", "Битгий хоцроорой."]],
      quiz: [{ q: "___ touch it! It's hot.", o: ["Not", "No", "Don't", "Doesn't"], a: 2 }] },
    { title: "Цагийн угтвар: in / on / at", explain: "at — цаг, тодорхой агшин (at 7 o'clock, at night). on — гараг, огноо (on Monday, on 5 May). in — сар, улирал, жил, өдрийн хэсэг (in July, in 2025, in the morning).",
      examples: [["The lesson starts at nine.", "Хичээл есөн цагт эхэлнэ."], ["My birthday is in March.", "Миний төрсөн өдөр гуравдугаар сард."]],
      quiz: [{ q: "I was born ___ 2008.", o: ["at", "on", "in", "by"], a: 2 }, { q: "See you ___ Friday.", o: ["in", "on", "at", "to"], a: 1 }] },
    { title: "Байршлын угтвар: in, on, under, next to...", explain: "in — дотор, on — дээр (гадаргуу), under — доор, next to — хажууд, between — хооронд, behind — ард, in front of — урд.",
      examples: [["The cat is under the bed.", "Муур орны доор байна."], ["The bank is between the shop and the school.", "Банк дэлгүүр, сургууль хоёрын хооронд."]],
      quiz: [{ q: "The keys are ___ the table. (дээр)", o: ["in", "on", "under", "at"], a: 1 }] },
    { title: "Асуух үгс: what, where, who, when, why, how", explain: "Асуух үг + туслах үйл үг + эзэн + үйл үг: Where do you live? What is your name? How old are you? How much / How many — хэдэн, хэр их.",
      examples: [["Where do you work?", "Чи хаана ажилладаг вэ?"], ["How many brothers have you got?", "Чи хэдэн ахтай вэ?"]],
      quiz: [{ q: "___ is your birthday? — In May.", o: ["Where", "Who", "When", "What"], a: 2 }] },
    { title: "Давтамжийн дайвар үг: always, usually, sometimes, never", explain: "Үндсэн үйл үгийн өмнө, харин be-ийн дараа ирнэ: I always get up early. / She is never late.",
      examples: [["I usually walk to school.", "Би ихэвчлэн сургууль руугаа алхаж явдаг."], ["He is always happy.", "Тэр үргэлж баяртай байдаг."]],
      quiz: [{ q: "Зөв өгүүлбэрийг сонго.", o: ["She never is late.", "She is never late.", "Never she is late.", "She is late never."], a: 1 }] },
    { title: "Present Continuous — Үргэлжилж буй одоо цаг", explain: "am/is/are + V-ing. Яг одоо болж буй үйл, түр зуурын нөхцөл. now, at the moment, today гэх мэт үгтэй хэрэглэнэ.",
      examples: [["I am reading a book now.", "Би одоо ном уншиж байна."], ["They aren't watching TV.", "Тэд зурагт үзэж байгаа юм биш."]],
      quiz: [{ q: "Look! It ___.", o: ["snows", "is snowing", "snowing", "snow"], a: 1 }] }
  ],
  "A2": [
    { title: "Past Continuous — Үргэлжилж байсан өнгөрсөн цаг", explain: "was/were + V-ing. Өнгөрсний тодорхой агшинд үргэлжилж байсан үйл. Ихэвчлэн Past Simple-тэй хамт: үргэлжилж байх үед өөр үйл болсон (when / while).",
      examples: [["I was cooking when you called.", "Чамайг залгахад би хоол хийж байсан."], ["While we were walking, it started to rain.", "Биднийг алхаж байхад бороо орж эхэлсэн."]],
      quiz: [{ q: "At 8 pm yesterday I ___ TV.", o: ["watched", "was watching", "am watching", "watch"], a: 1 }] },
    { title: "Тоолох / тоолж болохгүй нэр: some, any, much, many", explain: "Тоолж болдог: an apple, apples. Тоолж болдоггүй: water, money, information. some — хүүрнэх, any — үгүйсгэл, асуулт. many — тоолж болох, much — тоолж болохгүйтэй. a lot of — хоёуланд.",
      examples: [["Is there any milk?", "Сүү байна уу?"], ["I don't have much time.", "Надад тийм их цаг алга."]],
      quiz: [{ q: "How ___ money do you need?", o: ["many", "much", "lot", "some"], a: 1 }, { q: "There aren't ___ eggs.", o: ["some", "any", "much", "a"], a: 1 }] },
    { title: "Will ба going to — Ирээдүй", explain: "will — тухайн агшинд гаргасан шийдвэр, таамаглал, амлалт. going to — урьдчилан төлөвлөсөн зүйл, нүдэнд харагдаж буй нотолгоо.",
      examples: [["I'm tired. I think I'll go to bed.", "Ядарч байна. Унтъя гэж бодлоо."], ["We're going to visit Japan next year.", "Бид ирэх жил Япон руу явах гэж байгаа."]],
      quiz: [{ q: "The phone is ringing. — I ___ answer it.", o: ["am going to", "will", "going", "am"], a: 1 }] },
    { title: "Should / must / have to — Үүрэг ба зөвлөгөө", explain: "should — зөвлөгөө (хийсэн нь дээр). must — хатуу шаардлага, ярьж буй хүний үзэл. have to — гадны дүрэм, шаардлага. don't have to — шаардлагагүй; mustn't — хориглоно.",
      examples: [["You should see a doctor.", "Чи эмчид үзүүлэх хэрэгтэй."], ["You mustn't smoke here.", "Энд тамхи татаж болохгүй."]],
      quiz: [{ q: "Tomorrow is Sunday, so I ___ get up early.", o: ["mustn't", "don't have to", "shouldn't to", "have"], a: 1 }] },
    { title: "Дайвар үг үүсгэх (-ly)", explain: "Тэмдэг нэр + -ly → дайвар үг: quick → quickly, careful → carefully. Онцгой: good → well, fast → fast, hard → hard.",
      examples: [["She speaks English well.", "Тэр англиар сайн ярьдаг."], ["Drive carefully!", "Болгоомжтой жолоодоорой!"]],
      quiz: [{ q: "He runs very ___.", o: ["quick", "quickly", "quicky", "quicker"], a: 1 }] },
    { title: "Too ба enough", explain: "too + тэмдэг нэр — хэт (сөрөг утга): too expensive. тэмдэг нэр + enough — хангалттай: old enough. enough + нэр үг: enough money.",
      examples: [["This coffee is too hot to drink.", "Энэ кофе уухад хэт халуун байна."], ["He isn't tall enough to play basketball.", "Тэр сагсан бөмбөг тоглоход хангалттай өндөр биш."]],
      quiz: [{ q: "I can't buy it. It's ___ expensive.", o: ["enough", "too", "very much", "so much"], a: 1 }] },
    { title: "Тусагдахуун ба хамаатуулах төлөөний үг", explain: "Тусагдахуун: me, you, him, her, it, us, them. Хамаатуулах (нэр үггүй): mine, yours, his, hers, ours, theirs.",
      examples: [["Can you help me?", "Надад тусалж чадах уу?"], ["This bag isn't mine. It's hers.", "Энэ цүнх минийх биш. Түүнийх."]],
      quiz: [{ q: "Is this your pen? — Yes, it's ___.", o: ["my", "me", "mine", "I"], a: 2 }] },
    { title: "Gerund ба infinitive (энгийн)", explain: "Зарим үйл үгийн дараа -ing: enjoy, like, love, hate, finish, mind. Заримын дараа to + V: want, need, decide, hope, plan, would like.",
      examples: [["I enjoy reading.", "Би унших дуртай."], ["She wants to become a doctor.", "Тэр эмч болохыг хүсдэг."]],
      quiz: [{ q: "I finished ___ my homework.", o: ["do", "to do", "doing", "did"], a: 2 }, { q: "We decided ___ by train.", o: ["going", "to go", "go", "went"], a: 1 }] },
    { title: "Present Perfect + ever / never / just / yet", explain: "have/has + V3. ever — хэзээ нэгэн цагт (асуулт), never — хэзээ ч, just — дөнгөж сая, already — аль хэдийн, yet — одоохондоо (үгүйсгэл, асуулт).",
      examples: [["Have you ever eaten sushi?", "Чи суши идэж үзсэн үү?"], ["I haven't finished yet.", "Би одоохондоо дуусгаагүй байна."]],
      quiz: [{ q: "She has ___ arrived. She's in the kitchen.", o: ["yet", "ever", "just", "since"], a: 2 }] },
    { title: "Хөдөлгөөний угтвар: into, out of, across, through...", explain: "into — дотогш, out of — гадагш, across — хөндлөн гарах, through — дундуур нэвтрэх, along — дагуу, up / down — дээш / доош.",
      examples: [["We walked across the bridge.", "Бид гүүрээр хөндлөн гарсан."], ["The train went through the tunnel.", "Галт тэрэг хонгилоор дайрч өнгөрсөн."]],
      quiz: [{ q: "She jumped ___ the swimming pool.", o: ["into", "out of", "across", "along"], a: 0 }] },
    { title: "Буруу үйл үг (Irregular verbs)", explain: "Олон түгээмэл үйл үгийн өнгөрсөн цаг -ed биш: go → went → gone, see → saw → seen, buy → bought → bought, take → took → taken, write → wrote → written. Цээжлэх шаардлагатай.",
      examples: [["I bought a new phone yesterday.", "Би өчигдөр шинэ утас авсан."], ["We have seen that film.", "Бид тэр киног үзсэн."]],
      quiz: [{ q: "She ___ a letter to her friend last week.", o: ["writed", "wrote", "written", "writes"], a: 1 }] }
  ],
  "B1": [
    { title: "Present Perfect Continuous", explain: "have/has been + V-ing. Өнгөрсөнд эхэлсэн, одоо хүртэл үргэлжилж буй үйлийн үргэлжлэх хугацааг онцолно (for, since, how long).",
      examples: [["I have been studying English for three years.", "Би гурван жил англи хэл сурч байна."], ["It's been raining all day.", "Өдөржин бороо орж байна."]],
      quiz: [{ q: "How long ___ waiting?", o: ["are you", "have you been", "did you", "you have"], a: 1 }] },
    { title: "Past Perfect — Урьдчилсан өнгөрсөн цаг", explain: "had + V3. Өнгөрсний хоёр үйлээс аль түрүүнд болсныг заана.",
      examples: [["When I arrived, the film had already started.", "Намайг очиход кино аль хэдийн эхэлчихсэн байсан."], ["She had never flown before 2020.", "Тэр 2020 оноос өмнө онгоцоор нисч байгаагүй."]],
      quiz: [{ q: "By the time we got there, everyone ___.", o: ["left", "has left", "had left", "was leaving"], a: 2 }] },
    { title: "Used to / would — Өнгөрсний зуршил", explain: "used to + V — өмнө байсан боловч одоо байхгүй зуршил, байдал. would + V — өнгөрсний давтагддаг үйл (байдал илэрхийлэхгүй).",
      examples: [["I used to live in the countryside.", "Би өмнө нь хөдөө амьдардаг байсан."], ["Every summer we would ride horses.", "Зун бүр бид морь унадаг байлаа."]],
      quiz: [{ q: "She ___ have long hair, but now it's short.", o: ["use to", "used to", "was used to", "would to"], a: 1 }] },
    { title: "Таамаглалын модаль: must / might / can't", explain: "must be — бараг итгэлтэй (тийм байх нь), might/may/could be — магадгүй, can't be — тийм байх боломжгүй.",
      examples: [["He's been working all day. He must be tired.", "Тэр өдөржин ажилласан. Ядарсан байх нь гарцаагүй."], ["That can't be true!", "Тийм байж таарахгүй!"]],
      quiz: [{ q: "She isn't answering. She ___ be asleep.", o: ["can't", "might", "mustn't", "should"], a: 1 }] },
    { title: "Gerund ба infinitive (утга өөрчлөгдөх)", explain: "remember / forget / stop / try үйл үгийн дараа -ing болон to-V утга өөр: stop smoking (тамхиа хаях) vs stop to smoke (тамхи татахаар зогсох). remember doing (хийснээ санах) vs remember to do (хийхээ мартахгүй байх).",
      examples: [["Remember to lock the door.", "Хаалгаа түгжихээ мартуузай."], ["I stopped eating sugar.", "Би чихэр идэхээ больсон."]],
      quiz: [{ q: "I'll never forget ___ the Great Wall for the first time.", o: ["to see", "seeing", "see", "saw"], a: 1 }] },
    { title: "Question tags — Баталгаажуулах асуулт", explain: "Хүүрнэх эерэг өгүүлбэр → сөрөг tag, сөрөг → эерэг tag: It's cold, isn't it? You don't smoke, do you? Туслах үйл үгийг давтана.",
      examples: [["You're a student, aren't you?", "Чи оюутан, тийм үү?"], ["She can't swim, can she?", "Тэр сэлж чадахгүй, тийм биз?"]],
      quiz: [{ q: "They went to Paris, ___?", o: ["didn't they", "did they", "weren't they", "don't they"], a: 0 }] },
    { title: "Zero conditional — Ерөнхий үнэн", explain: "If + present simple, present simple. Үргэлж үнэн байдаг зүйл, шинжлэх ухааны баримт.",
      examples: [["If you heat ice, it melts.", "Мөсийг халаавал хайлдаг."], ["If I drink coffee at night, I can't sleep.", "Шөнө кофе уувал би унтаж чаддаггүй."]],
      quiz: [{ q: "If water ___ 100°C, it boils.", o: ["reach", "reaches", "will reach", "reached"], a: 1 }] },
    { title: "So ба such", explain: "so + тэмдэг нэр/дайвар үг: so beautiful. such + (a) + тэмдэг нэр + нэр үг: such a beautiful day. Үр дүнг that-аар залгана.",
      examples: [["The film was so boring that I fell asleep.", "Кино маш уйтгартай байсан тул би унтчихсан."], ["It was such a hot day.", "Маш халуун өдөр байлаа."]],
      quiz: [{ q: "She is ___ a kind person.", o: ["so", "such", "too", "very"], a: 1 }] },
    { title: "Харьцуулах бүтэц: as...as, the more... the more", explain: "as + тэмдэг нэр + as — адил; not as...as — тийм биш. the + харьцуулах зэрэг..., the + харьцуулах зэрэг — «хэдий чинээ... төдий чинээ».",
      examples: [["Darkhan is not as big as Ulaanbaatar.", "Дархан Улаанбаатар шиг том биш."], ["The more you practise, the better you get.", "Хэдий чинээ их дадлага хийнэ, төдий чинээ сайжирна."]],
      quiz: [{ q: "The ___ you study, the more you learn.", o: ["much", "more", "most", "many"], a: 1 }] },
    { title: "Хэмжээ: a few / few / a little / little", explain: "a few / few — тоолж болох нэртэй; a little / little — тоолж болохгүйтэй. a-тай нь «бага ч гэсэн бий» (эерэг), a-гүй нь «бараг байхгүй» (сөрөг).",
      examples: [["I have a few friends here.", "Энд хэдэн найз бий."], ["There is little hope.", "Найдвар бараг алга."]],
      quiz: [{ q: "Hurry up! We have ___ time.", o: ["few", "a few", "little", "many"], a: 2 }] },
    { title: "Phrasal verbs — Хэлц үйл үг", explain: "Үйл үг + угтвар/дайвар үг шинэ утга үүсгэнэ: look after (асрах), give up (хаях, бууж өгөх), find out (олж мэдэх), turn down (татгалзах), carry out (явуулах).",
      examples: [["She looks after her grandmother.", "Тэр эмээгээ асардаг."], ["The research was carried out in 2023.", "Судалгааг 2023 онд явуулсан."]],
      quiz: [{ q: "Don't ___ ! You can do it.", o: ["give up", "give in to", "look up", "find out"], a: 0 }] },
    { title: "Эсрэгцүүлэх холбоос: although, however, despite", explain: "although + өгүүлбэр; however — шинэ өгүүлбэрийн эхэнд таслалтай; despite / in spite of + нэр үг эсвэл V-ing.",
      examples: [["Although it was cold, we went out.", "Хүйтэн байсан ч бид гадагш гарсан."], ["Despite the rain, the match continued.", "Бороо орсон ч тоглолт үргэлжилсэн."]],
      quiz: [{ q: "___ being tired, she finished the report.", o: ["Although", "However", "Despite", "But"], a: 2 }] },
    { title: "Future Continuous", explain: "will be + V-ing. Ирээдүйн тодорхой агшинд үргэлжилж байх үйл.",
      examples: [["This time tomorrow I'll be flying to Seoul.", "Маргааш энэ үед би Сөүл рүү нисч явж байна."]],
      quiz: [{ q: "Don't call at 9. I ___ my exam.", o: ["will take", "will be taking", "take", "am take"], a: 1 }] }
  ],
  "B2": [
    { title: "Хувийн бус үйлдэгдэх хэв: It is said that...", explain: "It is said / believed / thought / reported that... эсвэл эзэн + is said to + V. Эрдэм шинжилгээний болон IELTS бичихэд объектив өнгө өгнө.",
      examples: [["It is believed that exercise reduces stress.", "Дасгал стрессийг бууруулдаг гэж үздэг."], ["He is said to be the richest man in the city.", "Түүнийг хотын хамгийн баян хүн гэдэг."]],
      quiz: [{ q: "It ___ that prices will rise next year.", o: ["expects", "is expected", "expected", "is expecting"], a: 1 }] },
    { title: "Wish / If only", explain: "Одоогийн харамсал: wish + past simple (I wish I had more time). Өнгөрсний харамсал: wish + past perfect (I wish I had studied). Бусдын үйлд гомдох: wish + would.",
      examples: [["I wish I could speak Chinese fluently.", "Хятадаар чөлөөтэй ярьдаг бол хичнээн сайн."], ["If only I hadn't missed the bus!", "Автобуснаасаа хоцроогүй бол яасан ч болоосой!"]],
      quiz: [{ q: "I wish I ___ harder at school. (өнгөрсөн)", o: ["studied", "had studied", "would study", "study"], a: 1 }] },
    { title: "Causative: have / get something done", explain: "Бусдаар хийлгэх: have/get + юм + V3. Жишээ: I had my hair cut (үсээ засуулсан).",
      examples: [["We're having our house painted.", "Бид байшингаа будуулж байгаа."], ["I need to get my phone repaired.", "Би утсаа засуулах хэрэгтэй."]],
      quiz: [{ q: "She ___ her car washed every week.", o: ["has", "makes", "does", "lets"], a: 0 }] },
    { title: "Future Perfect", explain: "will have + V3. Ирээдүйн тодорхой агшинаас өмнө дуусчихсан байх үйл (by 2030, by the end of...).",
      examples: [["By 2030, the population will have reached 4 million.", "2030 он гэхэд хүн ам 4 саяд хүрсэн байх болно."]],
      quiz: [{ q: "By next June, I ___ from university.", o: ["will graduate", "will have graduated", "graduate", "am graduating"], a: 1 }] },
    { title: "Өнгөрсний модаль: should have / might have / must have", explain: "should have + V3 — хийх ёстой байсан (харамсал, шүүмжлэл). must have — тийм болсон нь гарцаагүй. might/could have — магадгүй тийм болсон. can't have — болоогүй нь гарцаагүй.",
      examples: [["You should have told me earlier.", "Чи надад эрт хэлэх ёстой байсан."], ["She must have forgotten.", "Тэр мартсан байх нь гарцаагүй."]],
      quiz: [{ q: "The ground is wet. It ___ rained last night.", o: ["should have", "must have", "can't have", "would have"], a: 1 }] },
    { title: "Participle clauses — Үйлт нэрийн хэллэг", explain: "Тодотгол болон цагийн өгүүлбэрийг богиносгоно: V-ing (идэвхтэй), V3 (үйлдэгдэх), Having + V3 (өмнө нь болсон).",
      examples: [["Having finished the report, she went home.", "Тайлангаа дуусгаад тэр гэр рүүгээ явсан."], ["The data collected in 2020 shows a rise.", "2020 онд цуглуулсан өгөгдөл өсөлтийг харуулж байна."]],
      quiz: [{ q: "___ in 1990, the bridge is now unsafe.", o: ["Building", "Built", "Having built", "Builds"], a: 1 }] },
    { title: "Нөхцөлийн холбоос: unless, provided that, as long as", explain: "unless = if not. provided (that) / as long as — «...л бол» гэсэн нөхцөл. in case — «тохиолдож магадгүй тул».",
      examples: [["You won't pass unless you study.", "Хичээхгүй бол тэнцэхгүй."], ["You can borrow my car as long as you drive carefully.", "Болгоомжтой жолоодох л юм бол машинаа зээлүүлье."]],
      quiz: [{ q: "I'll take an umbrella ___ it rains.", o: ["unless", "in case", "provided", "as long as"], a: 1 }] },
    { title: "Хэлбэлзлийг тайлбарлах (IELTS Task 1)", explain: "Өсөх: rise, increase, grow, climb. Буурах: fall, decline, drop, decrease. Тогтвортой: remain stable, level off. Дайвар/тэмдэг нэр: sharply / a sharp rise, slightly / a slight fall, gradually, steadily, dramatically.",
      examples: [["Sales rose sharply in 2019.", "2019 онд борлуулалт огцом өссөн."], ["There was a gradual decline in the number of visitors.", "Зочдын тоо аажмаар буурсан."]],
      quiz: [{ q: "The figure ___ at around 40% after 2015. (тогтворжсон)", o: ["levelled off", "rose sharply", "dropped", "fluctuated wildly"], a: 0 }] },
    { title: "Нэр үгжүүлэлт (Nominalisation)", explain: "Үйл үг/тэмдэг нэрийг нэр үг болгож албан, эрдэм шинжилгээний өнгө өгнө: increase → an increase, develop → development, fail → failure. IELTS Writing-д өндөр оноо авахад тусална.",
      examples: [["The government's decision to raise taxes caused anger.", "Засгийн газрын татвар нэмэх шийдвэр уур хилэн төрүүлсэн."], ["The reduction of emissions is essential.", "Ялгарлыг бууруулах нь зайлшгүй."]],
      quiz: [{ q: "«People consume more» → «___ has increased»", o: ["Consume", "Consumption", "Consuming of", "Consumer"], a: 1 }] },
    { title: "Hedging — Болгоомжтой илэрхийлэл", explain: "Хэт туйлширсан дүгнэлтээс зайлсхийнэ: tend to, it seems that, may/might, arguably, to some extent, it could be argued that.",
      examples: [["Young people tend to spend more time online.", "Залуучууд онлайн илүү их цаг зарцуулах хандлагатай."], ["It could be argued that tourism does more harm than good.", "Аялал жуулчлал ашгаас илүү хор учруулдаг гэж хэлж болох юм."]],
      quiz: [{ q: "Хамгийн болгоомжтой хэлбэрийг сонго.", o: ["Technology destroys families.", "Technology always destroys families.", "Technology may weaken family relationships.", "Technology is 100% bad."], a: 2 }] },
    { title: "Онцлох do / does / did", explain: "Хүүрнэх өгүүлбэрт үйл үгийг онцлохдоо do/does/did + V: I do like it! Эсрэг санааг онцлоход ч хэрэглэнэ.",
      examples: [["I do understand your point, but I disagree.", "Таны санааг үнэхээр ойлгож байна, гэхдээ санал нийлэхгүй."]],
      quiz: [{ q: "She ___ call you yesterday — check your phone.", o: ["do", "did", "does", "was"], a: 1 }] },
    { title: "Үйл үгийн загвар: suggest, recommend, insist", explain: "suggest/recommend + V-ing эсвэл + that + эзэн + (should) V. «suggest to do» буруу.",
      examples: [["I suggest taking the train.", "Галт тэргээр явахыг санал болгож байна."], ["The doctor recommended that he rest.", "Эмч түүнийг амрахыг зөвлөсөн."]],
      quiz: [{ q: "He suggested ___ a taxi.", o: ["to take", "take", "taking", "took"], a: 2 }] }
  ],
  "C1": [
    { title: "Урвуу нөхцөл: Had I..., Should you..., Were it...", explain: "if-ийг орхиж туслах үйл үгийг урд гаргана: Had I known (= If I had known), Should you need help (= If you need), Were I you (= If I were you). Албан бичигт тохиромжтой.",
      examples: [["Should you have any questions, please contact us.", "Асуулт байвал бидэнтэй холбогдоно уу."], ["Were it not for his help, we would have failed.", "Түүний тусламж байгаагүй бол бид бүтэлгүйтэх байсан."]],
      quiz: [{ q: "___ I known about the traffic, I would have left earlier.", o: ["If", "Had", "Have", "Should"], a: 1 }] },
    { title: "Subjunctive — Шаардах хэв", explain: "essential / vital / important that, recommend / demand / insist that + эзэн + үйл үгийн үндсэн хэлбэр (-s-гүй, be хэвээр).",
      examples: [["It is essential that every child receive an education.", "Хүүхэд бүр боловсрол эзэмших нь зайлшгүй."], ["They demanded that he be dismissed.", "Тэд түүнийг ажлаас нь халахыг шаардсан."]],
      quiz: [{ q: "It is vital that the government ___ action now.", o: ["takes", "take", "took", "taking"], a: 1 }] },
    { title: "Үйлдэгдэх хэвийн нарийн хэлбэр: is thought to have...", explain: "Эзэн + be + V3 + to have + V3 — өнгөрсөнд болсон гэж үздэг зүйл. to be being + V3 гэх мэт нийлмэл хэлбэрүүд.",
      examples: [["The fire is thought to have started in the kitchen.", "Гал гал тогооноос эхэлсэн гэж үзэж байна."]],
      quiz: [{ q: "The painting is believed ___ in the 15th century.", o: ["to paint", "to have been painted", "painting", "to be paint"], a: 1 }] },
    { title: "Ellipsis ба substitution — Орхих, орлуулах", explain: "Давталтаас зайлсхийх: one/ones (нэр үг), do so (үйл үг), so/not (өгүүлбэр): I think so / I hope not. Туслах үйл үгээр төгсгөх: She can swim and so can I.",
      examples: [["Many people want to quit smoking, but few manage to do so.", "Олон хүн тамхиа хаяхыг хүсдэг ч цөөхөн нь чаддаг."], ["Will it rain? — I hope not.", "Бороо орох болов уу? — Орохгүй байгаасай."]],
      quiz: [{ q: "I'd like a coffee. Would you like ___ too?", o: ["it", "one", "so", "that"], a: 1 }] },
    { title: "Fronting — Өгүүлбэрийн хэсгийг урагшлуулах", explain: "Онцлохын тулд тусагдахуун, дайвар хэллэгийг өгүүлбэрийн эхэнд гаргана: Particularly important is... / Of greater concern is...",
      examples: [["Of greater concern is the rise in youth unemployment.", "Илүү санаа зовоосон зүйл бол залуучуудын ажилгүйдлийн өсөлт юм."], ["Gone are the days when people wrote letters.", "Хүмүүс захидал бичдэг байсан үе өнгөрсөн."]],
      quiz: [{ q: "Хамгийн зөв fronting өгүүлбэр:", o: ["Most worrying is the lack of funding.", "Most worrying the lack of funding is.", "Is most worrying the lack of funding.", "The lack most worrying is of funding."], a: 0 }] },
    { title: "Future in the past — Өнгөрсний ирээдүй", explain: "was/were going to, would, was about to, was to — өнгөрсний үүднээс ирээдүйг илэрхийлнэ. Ихэвчлэн биелээгүй төлөвлөгөө.",
      examples: [["I was going to call you, but I forgot.", "Чам руу залгах гэж байсан ч мартчихсан."], ["Little did they know that they would never meet again.", "Тэд дахин хэзээ ч уулзахгүй гэдгээ мэдээгүй."]],
      quiz: [{ q: "We ___ leave when it started snowing.", o: ["were about to", "are about to", "will", "had been"], a: 0 }] },
    { title: "Нарийн модаль: needn't have, would rather, had better", explain: "needn't have + V3 — хийсэн боловч шаардлагагүй байсан. didn't need to — шаардлагагүй тул хийгээгүй. would rather + V / + эзэн + past. had better + V — сэрэмжлүүлэг.",
      examples: [["You needn't have brought food — we had plenty.", "Хоол авчрах шаардлагагүй байсан — бидэнд их байсан."], ["I'd rather you didn't smoke here.", "Энд тамхи татахгүй байсан нь дээр."]],
      quiz: [{ q: "I bought tickets, but I ___ — entry was free!", o: ["didn't need to", "needn't have", "mustn't have", "hadn't"], a: 1 }] },
    { title: "Нийлмэл нэр үгийн хэллэг", explain: "Мэдээллийг нягт багтаахын тулд нэр үгийн хэллэгийг өргөтгөнө: тодотгол + нэр + угтвар хэллэг/тодотгол өгүүлбэр. Эрдэм шинжилгээний бичгийн онцлог.",
      examples: [["The rapid expansion of low-cost air travel over the past decade has increased emissions.", "Сүүлийн арван жилд хямд агаарын тээвэр хурдацтай өргөжсөн нь ялгарлыг нэмэгдүүлсэн."]],
      quiz: [{ q: "Аль нь илүү эрдэм шинжилгээний найруулга вэ?", o: ["Cities grew fast and this was a problem.", "The rapid growth of cities posed significant problems.", "Cities, they grew really fast.", "Fast cities grew problems."], a: 1 }] },
    { title: "Дискурс маркер (бичгийн уялдаа)", explain: "Нэмэх: furthermore, moreover. Эсрэгцүүлэх: nevertheless, conversely, on the contrary. Үр дагавар: consequently, thus, hence. Тодруулах: that is to say, in other words. Онцлох: notably, in particular.",
      examples: [["The policy was expensive; nevertheless, it proved effective.", "Бодлого үнэтэй байсан ч үр дүнтэй болох нь батлагдсан."]],
      quiz: [{ q: "Prices rose sharply; ___, demand fell.", o: ["moreover", "consequently", "for instance", "similarly"], a: 1 }] },
    { title: "It + тэмдэг нэр + that / to (Үнэлэх бүтэц)", explain: "It is widely acknowledged that..., It is crucial to..., It is hardly surprising that... — дүгнэлтийг объективоор илэрхийлнэ.",
      examples: [["It is hardly surprising that young people are moving to cities.", "Залуучууд хот руу нүүж байгаа нь гайхмаар зүйл биш."]],
      quiz: [{ q: "It is widely ___ that education reduces poverty.", o: ["accept", "accepting", "accepted", "acceptance"], a: 2 }] },
    { title: "Whereby, wherein, whereas — Албан холбоос", explain: "whereby — «...замаар/үүгээр» (by which), wherein — «үүнд» (in which), whereas — эсрэгцүүлэх «харин».",
      examples: [["They introduced a system whereby workers can choose their hours.", "Тэд ажилчид цагаа өөрсдөө сонгох тогтолцоо нэвтрүүлсэн."]],
      quiz: [{ q: "a scheme ___ students receive free meals", o: ["whereas", "whereby", "whenever", "wherever"], a: 1 }] },
    { title: "The + харьцуулах зэрэг ба нарийн харьцуулалт", explain: "considerably / far / significantly / marginally + харьцуулах зэрэг; twice as ... as; nowhere near as ... as; by far the + давамгай зэрэг.",
      examples: [["Coal is by far the cheapest source of energy.", "Нүүрс бол хамгийн хямд эрчим хүчний эх үүсвэр юм."], ["The figure was nowhere near as high as predicted.", "Үзүүлэлт таамагласан шиг тийм өндөр огт биш байлаа."]],
      quiz: [{ q: "Prices in 2020 were ___ higher than in 2010. (бага зэрэг)", o: ["marginally", "very", "much more", "by far"], a: 0 }] }
  ]
};
(function () {
  var G = window.IELTS.grammar;
  Object.keys(window.EN_GRAMMAR_MORE).forEach(function (lv) { G[lv] = (G[lv] || []).concat(window.EN_GRAMMAR_MORE[lv]); });
})();
