/* HSK 2.0 (хуучин стандарт, 2009–2021): 6 түвшин, нийт 5000 үг.
   Үг бүр: [ханз, пиньинь, англи, монгол] */
window.HSK2 = {
  name: "HSK 2.0 (хуучин)",
  levels: ["1", "2", "3", "4", "5", "6"],
  info: {
    "1": { words: 150, total: 150, cefr: "A1", desc: "Өдөр тутмын маш энгийн үг хэллэг, мэндчилгээ, тоо." },
    "2": { words: 150, total: 300, cefr: "A2", desc: "Энгийн өдөр тутмын харилцаа, гэр бүл, худалдаа." },
    "3": { words: 300, total: 600, cefr: "B1", desc: "Ажил, сургууль, аялалын үндсэн харилцаа." },
    "4": { words: 600, total: 1200, cefr: "B2", desc: "Олон сэдвээр чөлөөтэй ярилцах, уугуул хүнтэй харилцах." },
    "5": { words: 1300, total: 2500, cefr: "C1", desc: "Сонин, кино ойлгох, илтгэл тавих." },
    "6": { words: 2500, total: 5000, cefr: "C2", desc: "Хятад хэлээр бичгээр болон амаар чөлөөтэй илэрхийлэх." }
  },
  words: {
    "1": [
      ["爱", "ài", "love", "хайрлах"],
      ["八", "bā", "eight", "найм"],
      ["爸爸", "bàba", "dad", "аав"],
      ["杯子", "bēizi", "cup", "аяга"],
      ["北京", "Běijīng", "Beijing", "Бээжин"],
      ["不", "bù", "not", "үгүй, биш"],
      ["菜", "cài", "dish, vegetable", "хоол, ногоо"],
      ["茶", "chá", "tea", "цай"],
      ["吃", "chī", "to eat", "идэх"],
      ["出租车", "chūzūchē", "taxi", "такси"],
      ["大", "dà", "big", "том"],
      ["电脑", "diànnǎo", "computer", "компьютер"],
      ["电视", "diànshì", "television", "зурагт"],
      ["东西", "dōngxi", "thing", "юм, эд зүйл"],
      ["读", "dú", "to read", "унших"],
      ["飞机", "fēijī", "airplane", "онгоц"],
      ["狗", "gǒu", "dog", "нохой"],
      ["汉语", "Hànyǔ", "Chinese language", "хятад хэл"],
      ["好", "hǎo", "good", "сайн"],
      ["喝", "hē", "to drink", "уух"],
      ["家", "jiā", "home, family", "гэр, гэр бүл"],
      ["老师", "lǎoshī", "teacher", "багш"],
      ["妈妈", "māma", "mom", "ээж"],
      ["米饭", "mǐfàn", "cooked rice", "будаа"],
      ["你", "nǐ", "you", "чи"],
      ["朋友", "péngyou", "friend", "найз"],
      ["水", "shuǐ", "water", "ус"],
      ["天气", "tiānqì", "weather", "цаг агаар"],
      ["谢谢", "xièxie", "thank you", "баярлалаа"],
      ["学生", "xuésheng", "student", "сурагч"],
      ["医生", "yīshēng", "doctor", "эмч"],
      ["中国", "Zhōngguó", "China", "Хятад улс"]
    ],
    "2": [
      ["帮助", "bāngzhù", "to help", "туслах"],
      ["便宜", "piányi", "cheap", "хямд"],
      ["唱歌", "chànggē", "to sing", "дуу дуулах"],
      ["非常", "fēicháng", "very", "маш"],
      ["高兴", "gāoxìng", "happy, glad", "баяртай"],
      ["公司", "gōngsī", "company", "компани"],
      ["孩子", "háizi", "child", "хүүхэд"],
      ["回答", "huídá", "to answer", "хариулах"],
      ["机场", "jīchǎng", "airport", "нисэх буудал"],
      ["教室", "jiàoshì", "classroom", "анги танхим"],
      ["介绍", "jièshào", "to introduce", "танилцуулах"],
      ["咖啡", "kāfēi", "coffee", "кофе"],
      ["考试", "kǎoshì", "exam", "шалгалт"],
      ["快乐", "kuàilè", "happy, joyful", "жаргалтай"],
      ["旅游", "lǚyóu", "to travel", "аялах"],
      ["妹妹", "mèimei", "younger sister", "эмэгтэй дүү"],
      ["牛奶", "niúnǎi", "milk", "сүү"],
      ["跑步", "pǎobù", "to run, jog", "гүйх"],
      ["生日", "shēngrì", "birthday", "төрсөн өдөр"],
      ["手表", "shǒubiǎo", "wristwatch", "бугуйн цаг"],
      ["颜色", "yánsè", "color", "өнгө"],
      ["已经", "yǐjīng", "already", "аль хэдийн"],
      ["运动", "yùndòng", "sport, exercise", "спорт, дасгал"],
      ["准备", "zhǔnbèi", "to prepare", "бэлтгэх"],
      ["丈夫", "zhàngfu", "husband", "нөхөр"],
      ["眼睛", "yǎnjing", "eye", "нүд"]
    ],
    "3": [
      ["爱好", "àihào", "hobby", "хобби, сонирхол"],
      ["办法", "bànfǎ", "way, method", "арга"],
      ["比赛", "bǐsài", "competition", "тэмцээн"],
      ["变化", "biànhuà", "change", "өөрчлөлт"],
      ["词典", "cídiǎn", "dictionary", "толь бичиг"],
      ["地图", "dìtú", "map", "газрын зураг"],
      ["锻炼", "duànliàn", "to work out", "биеийн тамир хийх"],
      ["发烧", "fāshāo", "to have a fever", "халуурах"],
      ["附近", "fùjìn", "nearby", "ойролцоо"],
      ["关心", "guānxīn", "to care about", "санаа тавих"],
      ["环境", "huánjìng", "environment", "орчин"],
      ["健康", "jiànkāng", "healthy, health", "эрүүл мэнд"],
      ["节日", "jiérì", "festival, holiday", "баяр"],
      ["经常", "jīngcháng", "often", "байнга"],
      ["决定", "juédìng", "to decide", "шийдэх"],
      ["满意", "mǎnyì", "satisfied", "сэтгэл хангалуун"],
      ["认真", "rènzhēn", "conscientious, serious", "хичээнгүй"],
      ["世界", "shìjiè", "world", "дэлхий"],
      ["习惯", "xíguàn", "habit", "зуршил"],
      ["兴趣", "xìngqù", "interest", "сонирхол"],
      ["选择", "xuǎnzé", "to choose", "сонгох"],
      ["重要", "zhòngyào", "important", "чухал"],
      ["周末", "zhōumò", "weekend", "амралтын өдөр"],
      ["银行", "yínháng", "bank", "банк"],
      ["冰箱", "bīngxiāng", "refrigerator", "хөргөгч"]
    ],
    "4": [
      ["安排", "ānpái", "to arrange", "зохион байгуулах"],
      ["保护", "bǎohù", "to protect", "хамгаалах"],
      ["报名", "bàomíng", "to sign up", "бүртгүүлэх"],
      ["毕业", "bìyè", "to graduate", "төгсөх"],
      ["表扬", "biǎoyáng", "to praise", "магтах"],
      ["材料", "cáiliào", "material", "материал"],
      ["成功", "chénggōng", "success", "амжилт"],
      ["诚实", "chéngshí", "honest", "үнэнч шударга"],
      ["导游", "dǎoyóu", "tour guide", "аяллын хөтөч"],
      ["方法", "fāngfǎ", "method", "арга зүй"],
      ["感动", "gǎndòng", "to be moved", "сэтгэл хөдлөх"],
      ["估计", "gūjì", "to estimate", "тооцоолох, таамаглах"],
      ["经验", "jīngyàn", "experience", "туршлага"],
      ["竞争", "jìngzhēng", "to compete", "өрсөлдөх"],
      ["困难", "kùnnan", "difficulty", "бэрхшээл"],
      ["浪费", "làngfèi", "to waste", "үрэн таран хийх"],
      ["理想", "lǐxiǎng", "ideal, dream", "хүсэл мөрөөдөл"],
      ["签证", "qiānzhèng", "visa", "виз"],
      ["缺点", "quēdiǎn", "shortcoming", "дутагдал"],
      ["熟悉", "shúxī", "to be familiar with", "сайн мэдэх, дасах"],
      ["温度", "wēndù", "temperature", "температур"],
      ["信心", "xìnxīn", "confidence", "итгэл"],
      ["责任", "zérèn", "responsibility", "хариуцлага"],
      ["质量", "zhìliàng", "quality", "чанар"],
      ["优点", "yōudiǎn", "strong point", "давуу тал"]
    ],
    "5": [
      ["把握", "bǎwò", "to grasp; certainty", "атгах; итгэлтэй байх"],
      ["宝贵", "bǎoguì", "precious", "үнэ цэнэтэй"],
      ["补充", "bǔchōng", "to supplement", "нөхөх"],
      ["采访", "cǎifǎng", "to interview", "ярилцлага авах"],
      ["承担", "chéngdān", "to undertake", "үүрэх, хариуцах"],
      ["传统", "chuántǒng", "tradition", "уламжлал"],
      ["促进", "cùjìn", "to promote", "дэмжих, хурдасгах"],
      ["代表", "dàibiǎo", "to represent", "төлөөлөх"],
      ["发挥", "fāhuī", "to bring into play", "чадвараа гаргах"],
      ["改善", "gǎishàn", "to improve", "сайжруулах"],
      ["观念", "guānniàn", "concept, notion", "үзэл баримтлал"],
      ["规律", "guīlǜ", "law, pattern", "зүй тогтол"],
      ["合同", "hétong", "contract", "гэрээ"],
      ["积极", "jījí", "positive, active", "идэвхтэй"],
      ["价值", "jiàzhí", "value", "үнэ цэнэ"],
      ["克服", "kèfú", "to overcome", "даван туулах"],
      ["灵活", "línghuó", "flexible", "уян хатан"],
      ["秘书", "mìshū", "secretary", "нарийн бичиг"],
      ["迫切", "pòqiè", "urgent", "яаралтай, нэн шаардлагатай"],
      ["设施", "shèshī", "facilities", "байгууламж"],
      ["突出", "tūchū", "prominent", "тод, онцгой"],
      ["效率", "xiàolǜ", "efficiency", "үр ашиг"],
      ["业余", "yèyú", "spare-time, amateur", "чөлөөт цагийн, сонирхогч"],
      ["资源", "zīyuán", "resources", "нөөц баялаг"],
      ["移民", "yímín", "to immigrate", "цагаачлах"]
    ],
    "6": [
      ["颁布", "bānbù", "to promulgate", "зарлан тунхаглах"],
      ["弊端", "bìduān", "drawback, abuse", "сөрөг тал"],
      ["博大精深", "bódà jīngshēn", "broad and profound", "өргөн бөгөөд гүнзгий"],
      ["层出不穷", "céngchū bùqióng", "to emerge endlessly", "ар араасаа тасралтгүй гарах"],
      ["诧异", "chàyì", "astonished", "гайхширах"],
      ["倡导", "chàngdǎo", "to advocate", "уриалах, сурталчлах"],
      ["斟酌", "zhēnzhuó", "to deliberate", "нягтлан бодох"],
      ["端正", "duānzhèng", "upright, proper", "зөв шулуун"],
      ["繁华", "fánhuá", "bustling, flourishing", "хөл хөдөлгөөн ихтэй, цэцэглэн хөгжсөн"],
      ["尴尬", "gāngà", "awkward", "эвгүй, ичмээр"],
      ["怀念", "huáiniàn", "to cherish the memory of", "дурсан санах"],
      ["精益求精", "jīngyì qiújīng", "to strive for perfection", "улам төгөлдөржүүлэх"],
      ["慷慨", "kāngkǎi", "generous", "өгөөмөр"],
      ["履行", "lǚxíng", "to fulfill", "биелүүлэх"],
      ["茫然", "mángrán", "at a loss", "будилах, мэдэхгүй болох"],
      ["默契", "mòqì", "tacit understanding", "үггүй ойлголцол"],
      ["潜力", "qiánlì", "potential", "далд чадавх"],
      ["迄今为止", "qìjīn wéizhǐ", "so far, up to now", "өнөөг хүртэл"],
      ["深奥", "shēn'ào", "profound, abstruse", "гүн гүнзгий, ойлгоход хэцүү"],
      ["蔚蓝", "wèilán", "azure", "номин цэнхэр"],
      ["协调", "xiétiáo", "to coordinate", "зохицуулах"],
      ["一丝不苟", "yìsī bùgǒu", "meticulous", "нэг бүрчлэн нягт нямбай"],
      ["酝酿", "yùnniàng", "to brew; to deliberate", "исгэх; боловсруулах"],
      ["朝气蓬勃", "zhāoqì péngbó", "full of vigor", "эрч хүчээр бялхсан"],
      ["与日俱增", "yǔ rì jù zēng", "to increase day by day", "өдрөөс өдөрт нэмэгдэх"]
    ]
  }
};
