/* HSK 3.0 (шинэ стандарт, 2021 оноос): 3 шат, 9 түвшин, нийт 11092 үг, 3000 ханз.
   Үг бүр: [ханз, пиньинь, англи, монгол] */
window.HSK3 = {
  name: "HSK 3.0 (шинэ)",
  levels: ["1", "2", "3", "4", "5", "6", "7-9"],
  info: {
    "1": { words: 500, total: 500, chars: 300, grammar: 48, stage: "Анхан шат", desc: "Өдөр тутмын хамгийн энгийн харилцаа. 2.0-ийн 1-р түвшнээс 3 дахин их үгтэй." },
    "2": { words: 772, total: 1272, chars: 600, grammar: 81, stage: "Анхан шат", desc: "Гэр бүл, сургууль, худалдаа зэрэг өдөр тутмын сэдэв." },
    "3": { words: 973, total: 2245, chars: 900, grammar: 81, stage: "Анхан шат", desc: "Ажил, сургалт, аялалын нийтлэг нөхцөл байдалд харилцах." },
    "4": { words: 1000, total: 3245, chars: 1200, grammar: 76, stage: "Дунд шат", desc: "Нийгэм, соёлын сэдвээр ярилцах, энгийн эх орчуулах." },
    "5": { words: 1071, total: 4316, chars: 1500, grammar: 71, stage: "Дунд шат", desc: "Нарийн сэдвээр санаагаа логиктой илэрхийлэх." },
    "6": { words: 1140, total: 5456, chars: 1800, grammar: 67, stage: "Дунд шат", desc: "Мэргэжлийн болон хийсвэр сэдвийг ойлгох, хэлэлцэх." },
    "7-9": { words: 5636, total: 11092, chars: 3000, grammar: 148, stage: "Ахисан шат", desc: "Эрдэм шинжилгээ, мэргэжлийн түвшинд чөлөөтэй хэрэглэх, орчуулга." }
  },
  words: {
    "1": [
      ["白天", "báitiān", "daytime", "өдөр (гэгээтэй цаг)"],
      ["帮", "bāng", "to help", "туслах"],
      ["饱", "bǎo", "full (after eating)", "цадах"],
      ["别", "bié", "don't", "битгий"],
      ["长", "cháng", "long", "урт"],
      ["唱", "chàng", "to sing", "дуулах"],
      ["穿", "chuān", "to wear", "өмсөх"],
      ["床", "chuáng", "bed", "ор"],
      ["错", "cuò", "wrong", "буруу"],
      ["打开", "dǎkāi", "to open", "нээх"],
      ["弟弟", "dìdi", "younger brother", "эрэгтэй дүү"],
      ["对", "duì", "correct", "зөв"],
      ["房间", "fángjiān", "room", "өрөө"],
      ["高", "gāo", "tall, high", "өндөр"],
      ["哥哥", "gēge", "older brother", "ах"],
      ["贵", "guì", "expensive", "үнэтэй"],
      ["欢迎", "huānyíng", "welcome", "тавтай морил"],
      ["课", "kè", "lesson", "хичээл"],
      ["快", "kuài", "fast", "хурдан"],
      ["冷", "lěng", "cold", "хүйтэн"],
      ["门", "mén", "door", "хаалга"],
      ["名字", "míngzi", "name", "нэр"],
      ["票", "piào", "ticket", "тасалбар"],
      ["晚上", "wǎnshang", "evening", "орой"],
      ["问", "wèn", "to ask", "асуух"],
      ["洗", "xǐ", "to wash", "угаах"],
      ["新", "xīn", "new", "шинэ"],
      ["早上", "zǎoshang", "morning", "өглөө"]
    ],
    "2": [
      ["安静", "ānjìng", "quiet", "нам гүм"],
      ["比较", "bǐjiào", "relatively; to compare", "харьцангуй; харьцуулах"],
      ["必须", "bìxū", "must", "заавал"],
      ["参加", "cānjiā", "to take part in", "оролцох"],
      ["城市", "chéngshì", "city", "хот"],
      ["当然", "dāngrán", "of course", "мэдээж"],
      ["地方", "dìfang", "place", "газар"],
      ["方便", "fāngbiàn", "convenient", "тохиромжтой"],
      ["感冒", "gǎnmào", "to catch a cold", "ханиад хүрэх"],
      ["关系", "guānxi", "relationship", "харилцаа"],
      ["害怕", "hàipà", "to be afraid", "айх"],
      ["坏", "huài", "bad, broken", "муу, эвдэрсэн"],
      ["检查", "jiǎnchá", "to check", "шалгах"],
      ["节目", "jiémù", "program, show", "нэвтрүүлэг"],
      ["句子", "jùzi", "sentence", "өгүүлбэр"],
      ["历史", "lìshǐ", "history", "түүх"],
      ["普通话", "pǔtōnghuà", "Mandarin", "нийтлэг хятад хэл"],
      ["容易", "róngyì", "easy", "амархан"],
      ["声音", "shēngyīn", "sound, voice", "дуу чимээ"],
      ["照片", "zhàopiàn", "photo", "зураг"],
      ["表示", "biǎoshì", "to express", "илэрхийлэх"],
      ["久", "jiǔ", "long (time)", "удаан"],
      ["满", "mǎn", "full", "дүүрэн"],
      ["花", "huā", "to spend; flower", "зарцуулах; цэцэг"]
    ],
    "3": [
      ["保持", "bǎochí", "to maintain", "хадгалах, тогтоон барих"],
      ["表演", "biǎoyǎn", "to perform", "тоглолт үзүүлэх"],
      ["产生", "chǎnshēng", "to produce, arise", "үүсэх, бий болох"],
      ["成绩", "chéngjì", "grade, result", "дүн, амжилт"],
      ["程度", "chéngdù", "degree, level", "түвшин, хэмжээ"],
      ["发展", "fāzhǎn", "to develop", "хөгжих"],
      ["方向", "fāngxiàng", "direction", "чиглэл"],
      ["规定", "guīdìng", "rule, regulation", "журам, дүрэм"],
      ["计划", "jìhuà", "plan", "төлөвлөгөө"],
      ["技术", "jìshù", "technology, skill", "технологи, ур чадвар"],
      ["经济", "jīngjì", "economy", "эдийн засаг"],
      ["科学", "kēxué", "science", "шинжлэх ухаан"],
      ["能力", "nénglì", "ability", "чадвар"],
      ["情况", "qíngkuàng", "situation", "нөхцөл байдал"],
      ["区别", "qūbié", "difference", "ялгаа"],
      ["社会", "shèhuì", "society", "нийгэм"],
      ["实际", "shíjì", "actual, real", "бодит"],
      ["提高", "tígāo", "to raise, improve", "дээшлүүлэх"],
      ["文化", "wénhuà", "culture", "соёл"],
      ["相信", "xiāngxìn", "to believe", "итгэх"],
      ["印象", "yìnxiàng", "impression", "сэтгэгдэл"],
      ["影响", "yǐngxiǎng", "influence", "нөлөө"],
      ["原因", "yuányīn", "reason, cause", "шалтгаан"],
      ["支持", "zhīchí", "to support", "дэмжих"],
      ["组织", "zǔzhī", "to organize", "зохион байгуулах"]
    ],
    "4": [
      ["避免", "bìmiǎn", "to avoid", "зайлсхийх"],
      ["处理", "chǔlǐ", "to handle", "шийдвэрлэх, боловсруулах"],
      ["措施", "cuòshī", "measure, step", "арга хэмжээ"],
      ["发达", "fādá", "developed", "хөгжингүй"],
      ["反映", "fǎnyìng", "to reflect", "тусгах"],
      ["分析", "fēnxī", "to analyze", "шинжлэх, задлан шинжлэх"],
      ["根据", "gēnjù", "according to", "үндэслэн"],
      ["公平", "gōngpíng", "fair", "шударга"],
      ["基础", "jīchǔ", "foundation", "суурь"],
      ["降低", "jiàngdī", "to reduce", "бууруулах"],
      ["结构", "jiégòu", "structure", "бүтэц"],
      ["具体", "jùtǐ", "concrete, specific", "тодорхой"],
      ["理解", "lǐjiě", "to understand", "ойлгох"],
      ["目标", "mùbiāo", "goal", "зорилго"],
      ["平衡", "pínghéng", "balance", "тэнцвэр"],
      ["趋势", "qūshì", "trend", "чиг хандлага"],
      ["确定", "quèdìng", "to determine", "тогтоох, баталгаажуулах"],
      ["消费", "xiāofèi", "to consume", "хэрэглэх"],
      ["效果", "xiàoguǒ", "effect", "үр дүн"],
      ["优势", "yōushì", "advantage", "давуу тал"],
      ["状态", "zhuàngtài", "state, condition", "байдал"],
      ["对象", "duìxiàng", "target, partner", "объект; хань"]
    ],
    "5": [
      ["本质", "běnzhì", "essence", "мөн чанар"],
      ["策略", "cèlüè", "strategy", "стратеги"],
      ["承认", "chéngrèn", "to admit", "хүлээн зөвшөөрөх"],
      ["持续", "chíxù", "to continue", "үргэлжлэх"],
      ["冲突", "chōngtū", "conflict", "мөргөлдөөн"],
      ["贡献", "gòngxiàn", "contribution", "хувь нэмэр"],
      ["广泛", "guǎngfàn", "extensive", "өргөн хүрээтэй"],
      ["机制", "jīzhì", "mechanism", "механизм"],
      ["激烈", "jīliè", "intense, fierce", "ширүүн"],
      ["谨慎", "jǐnshèn", "cautious", "болгоомжтой"],
      ["矛盾", "máodùn", "contradiction", "зөрчил"],
      ["渠道", "qúdào", "channel", "суваг"],
      ["权利", "quánlì", "right", "эрх"],
      ["实施", "shíshī", "to implement", "хэрэгжүүлэх"],
      ["适应", "shìyìng", "to adapt", "дасан зохицох"],
      ["体系", "tǐxì", "system", "тогтолцоо"],
      ["维护", "wéihù", "to safeguard", "хамгаалах, сахих"],
      ["现象", "xiànxiàng", "phenomenon", "үзэгдэл"],
      ["意识", "yìshí", "consciousness, awareness", "ухамсар"],
      ["运用", "yùnyòng", "to apply, use", "ашиглах"]
    ],
    "6": [
      ["摆脱", "bǎituō", "to get rid of", "ангижрах"],
      ["动态", "dòngtài", "dynamic; trend", "динамик; явц"],
      ["繁荣", "fánróng", "prosperous", "цэцэглэн хөгжих"],
      ["合理", "hélǐ", "reasonable", "оновчтой, зохистой"],
      ["宏观", "hóngguān", "macro", "макро"],
      ["局限", "júxiàn", "to limit; limitation", "хязгаарлалт"],
      ["理念", "lǐniàn", "philosophy, idea", "үзэл санаа"],
      ["落实", "luòshí", "to carry out", "хэрэгжүүлэх"],
      ["模式", "móshì", "model, pattern", "загвар"],
      ["前景", "qiánjǐng", "prospect", "хэтийн төлөв"],
      ["倾向", "qīngxiàng", "tendency", "хандлага"],
      ["实质", "shízhì", "substance, essence", "мөн чанар"],
      ["塑造", "sùzào", "to shape", "бүтээх, бий болгох"],
      ["调整", "tiáozhěng", "to adjust", "тохируулах"],
      ["推动", "tuīdòng", "to promote, push", "түлхэц өгөх"],
      ["微观", "wēiguān", "micro", "микро"],
      ["依赖", "yīlài", "to depend on", "хамааралтай байх"],
      ["整合", "zhěnghé", "to integrate", "нэгтгэх"],
      ["转型", "zhuǎnxíng", "transformation", "шилжилт, хувирал"],
      ["颠覆", "diānfù", "to overturn", "эргүүлэх, үгүйсгэх"]
    ],
    "7-9": [
      ["跌宕起伏", "diēdàng qǐfú", "full of ups and downs", "эрс өөрчлөлттэй"],
      ["耐人寻味", "nài rén xún wèi", "thought-provoking", "эргэцүүлэм"],
      ["众所周知", "zhòngsuǒ zhōuzhī", "as everyone knows", "бүгдэд ил тод"],
      ["潜移默化", "qiányí mòhuà", "imperceptible influence", "үл анзаарагдам нөлөө"],
      ["举足轻重", "jǔzú qīngzhòng", "of decisive importance", "шийдвэрлэх ач холбогдолтой"],
      ["相辅相成", "xiāngfǔ xiāngchéng", "to complement each other", "бие биеэ нөхөх"],
      ["与时俱进", "yǔ shí jù jìn", "to keep pace with the times", "цаг үетэйгээ хөл нийлүүлэх"],
      ["脱颖而出", "tuōyǐng ér chū", "to stand out", "бусдаас тодрох"],
      ["刻不容缓", "kè bù róng huǎn", "extremely urgent", "нэн яаралтай"],
      ["不可思议", "bùkě sīyì", "inconceivable", "итгэмээргүй"],
      ["博弈", "bóyì", "game, contest", "тоглоом, тэмцэл"],
      ["瓶颈", "píngjǐng", "bottleneck", "гацаа"],
      ["契机", "qìjī", "opportunity, turning point", "боломж, эргэлтийн цэг"],
      ["渗透", "shèntòu", "to permeate", "нэвчих"],
      ["诠释", "quánshì", "to interpret", "тайлбарлах"],
      ["蕴含", "yùnhán", "to contain, imply", "агуулах"],
      ["遏制", "èzhì", "to curb", "хязгаарлах, таслан зогсоох"],
      ["范畴", "fànchóu", "category", "ангилал, хүрээ"]
    ]
  }
};
